### ISSUE TITLE
Get ready for VVV18 

### ISSUE THREAD

**Issue by traversaro** [vvv18-dynamics/vvv18-dynamics.github.io#1]
* [x] Migrate https://github.com/vvv-school/tutorial_impedance-control to iDynTree + RemoteControlBoardRemapper 
* [x] Migrate https://github.com/vvv-school/tutorial_impedance-control-simulink to WB-Toolbox 3 
* [x] Migrate https://github.com/vvv-school/assignment_computed-torque to iDynTree + RemoteControlBoardRemapper 
* [x] Migrate https://github.com/vvv-school/assignment_computed-torque-simulink to WB-Toolbox 3 
* [x] Verify that all the RTF machinery for the grading still works 
* [x] Create the assignments in the GitHub classroom 
* [x] Evaluate if it make sense to have some incremental grading

**Comment by traversaro** [comment]
cc @diegoferigo @pattacini @DanielePucci

**Comment by traversaro** [comment]
For all the repos, I think it is a good idea to tag the current state as `vvv17` to keep a snapshot of the current state.

**Comment by traversaro** [comment]
A low hanging fruit that would also help with the logistics of the Gazebo simulation would be to have the tutorial and the first step of the assignment to be done only on a simple model (double pendulum) that runs in Gazebo, and switch to the iCub case only as an advanced assignment.

**Comment by diegoferigo** [comment]
> A low hanging fruit that would also help with the logistics of the Gazebo simulation would be to have the tutorial and the first step of the assignment to be done only on a simple model (double pendulum) that runs in Gazebo, and switch to the iCub case only as an advanced assignment.

This would require some work on the models too, it's not so so straightforward.

I'll be full time on this starting from Monday.

**Comment by traversaro** [comment]
I am porting the test of assignment_computed-torque away to not depend on the yarp-WBI, as that part is shared with assignment_computed-torque-simulink as soon as I have finished we can copy it to the simulink assignment. cc @diegoferigo

**Comment by traversaro** [comment]
I finished updating the test in https://github.com/vvv-school/assignment_computed-torque/pull/2 . 
cc @diegoferigo Can you propagate the tests to the simulink when you update to WB3.0 ? Thanks!

**Comment by diegoferigo** [comment]
I already ported the models, I need to figure out how the tests work. We
can meet tomorrow morning and merge our parts.

**Comment by traversaro** [comment]
I tested that all the grading still works, and I also add the yarpmanager applications and pimped up the README of the assignment in https://github.com/vvv-school/assignment_computed-torque/pull/2 . 
Unfortunately now we are out of time for adding incremental grading or using a simpler model, but I still think it would be a great idea for next year.

**Comment by traversaro** [comment]
cc @diegoferigo please check the tickbox when you will update the simulink-based assignement, thanks!

**Comment by diegoferigo** [comment]
@pattacini @DanielePucci I ported the models to the new version of the toolbox, and from the students side everything should be fine.

However, today with @traversaro we dedicated some time to get the smoke-test working for the Simulink assignment and we run into unknown problems. The C++ side is working fine, tomorrow morning we're going to dedicate some more time to it.
